### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by subhojit777**
This changes/fixes/improves #15;

 - [x] I have read the [contribution guidelines][Contributing]
 - [ ] This change has tests (remove for doc only)
 - [ ] This change has documentation
 - [x] Corresponds to issue (#15 )

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by HeroicKatora** [comment]
This seems to be fine for me, does the compilation error happen on nightly?

**Comment by subhojit777** [comment]
`rustc 1.30.1 (1433507eb 2018-11-07)`

**Comment by HeroicKatora** [comment]
Weird, I can't replicate it with exactly the same compiler version. 

Maybe your work is based on some intermediate commit in a longer commit series. Can you try to base your work on the tag `v0.4.0-preview.0`? Note that the development branch is expected to change a lot, including breaking changes and non-compiling versions but only all tagged versions (aka. those published to <crates.io>) should work correctly. Still, your patch seems to be based on commit e6211cb855395f4d52c7c4daed451fab06e68398 which I can compile fine.

**Comment by subhojit777** [comment]
I was not able to compile with the `0.4.0-preview.0` version. There is a conflict with `ring` crate - https://github.com/HeroicKatora/oxide-auth/issues/15#issuecomment-435942381

**Comment by HeroicKatora** [comment]
Sorry that I never got around to this as it was a preview version and I could reproduce it. This should not happen in `v0.4` release.
